rho calculator added

diff --git a/multi_g_rdf b/multi_g_rdf
--- a/multi_g_rdf
+++ b/multi_g_rdf
@@ -205,7 +205,20 @@ for ((i=0;i<$np;i++)); do
   this_lines="$(sed -n '$=' "$this_out")" || die "linecount of $this_out failed"
   [ -z "$this_lines" ] && die "linecount of $this_out was empty"
   [ -z "$lines" ] && lines="$this_lines"
-  [ $this_lines -eq $lines ] || die "Number of data lines differs for $fbase nr $i - $this_lines vs $lines lines"
+  [ $this_lines -lt $lines ] && lines="$this_lines"
+done
+
+qecho "Checking output"
+for ((i=0;i<$np;i++)); do
+  np0="$(printf "%02i" $i)"
+  this_out="${sout/NP/$np0}"
+  [ -f "$this_out" ] || die "Could not find $this_out"
+  this_lines="$(sed -n '$=' "$this_out")" || die "linecount of $this_out failed"
+  [ -z "$this_lines" ] && die "linecount of $this_out was empty"
+  if [ "$this_lines" -gt "$lines" ]; then
+      echo "head -"$lines $this_out | sh > temp
+      mv temp $this_out
+  fi
 done
 
 qecho "Calculating average"
